### PR TITLE
Update to Glue Notebook

### PR DESCRIPTION
**Pull request by jrobrien91**
Update of Glue Notebook for OLCF, with additional comments and streamlined

### CODE REVIEW

**Comment by mgrover1** [comment]
@jrobrien91 - do these Dask issues happen everytime to run this notebook?

**Comment by jrobrien91** [comment]
@mgrover1 yah let's move this to draft. I forgot I already submitted this. Getting some errors I'd like help on

**Comment by mgrover1** [comment]
Happy to help :)

**Comment by jrobrien91** [comment]
thanks for help with the dask cluster. Still some proj errors on ALCF but is working well

**Comment by mgrover1** [comment]
YAY! Yeah... registering proj stuff on HPC can be a hassle sometimes

**Pull request closed without merging**
