### PR TITLE
ENH: ACT Discovery and I/O Handling of In-situ Data

### PR DESCRIPTION
**Pull request by jrobrien91**
Radar Columns and In-Situ Sensor (RadCLss) Notebook. Updated to include the use of ACT for in-situ data discovery and metadata handling/correction. Notebook streamlined with the addition of 'processing keywords' that allow user to easily change desired date of processing / location of data.

### CODE REVIEW

**Comment by jrobrien91** [comment]
Didn't catch the errors with the CMAC2.0 files. Adding another commit

**Comment by jrobrien91** [comment]
I ended up removing the plotting from this so it can serve as a quick notebook to create the matched dataset. Planning on adding a new notebook exploring the Gridded and Matched VAPs this upcoming week

**Comment by jrobrien91** [comment]
There was a slight bug matching the in-situ data files with the extracted columns, if you had another date already downloaded within your in-situ data directory. Added DATE to the glob search for these in-situ files so we are grabbing the correct dates to merge now. Additionally, fixed a small bug in interpolating RWP heights to the radar column. Should be good to go now.

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Great work @jrobrien91 ! This looks amazing! Just a couple of minor suggestions.

**Review by mgrover1 — APPROVED** [review]
Great! Thanks @jrobrien91

**Pull request merged**
